name: Build and Pack

on:
  push:
    tags:
      - 'v*'

env:
  RUSTFLAGS: -Dwarnings

jobs:
  pack:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [x86_64-pc-windows-msvc, aarch64-pc-windows-msvc]
        rust: [stable]
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        target: ${{ matrix.target }}
        profile: minimal
        override: true
        components: rustfmt

    - name: build
      run: cargo build --release --target ${{ matrix.target }}

    - name: fmt
      run: cargo fmt --all -- --check
      if: matrix.rust == 'stable'

    - name: pack
      uses: actions/upload-artifact@v2
      with:
        name: 'giffun_${{ matrix.target }}_release'
        path: '.\target\${{ matrix.target }}\release\giffun*'